import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {CONTRACT_ADDRESS,connectWallet,makeReadClient,readContract,waitTransaction,writeContract} from './genlayer';
import {VERSION,NETWORK,receiptReadable,sameAddress,loadJournal,saveJournal} from './transactions.js';
import './style.css'; import './verification.css';
const EXPLORER='https://explorer-studio.genlayer.com';
const short=v=>v?`${String(v).slice(0,10)}…${String(v).slice(-6)}`:'—';
const route=()=>window.location.hash.slice(1)||'/'; const go=p=>window.location.hash=p;
const dump=v=>JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x,2);
const gen=t=>{if(!/^\d+(\.\d{1,18})?$/.test(t)||Number(t)<=0)throw Error('Enter a positive GEN amount.');const[a,b='']=t.split('.');return BigInt(a)*10n**18n+BigInt(b.padEnd(18,'0'));};
const defaults={beneficiary:'',amount:'0.000001',owner:'macdon3202',repository:'IMPACTRAIL',base:'',target:'',artifactPath:'npm-package/index.js',artifactSha256:'',releaseTag:'',milestone:'',minimumCommits:'1',minimumContributors:'1',coverageStart:String(Math.floor(Date.now()/1000)-86400),duration:'180',partialBps:'5000',npmPackage:'@macdon3202/impactrail-verification',npmVersion:'1.0.0',verificationCommit:'19e1c7ee715f37cc1d7a23ba8df7695e9938de29',workflowPath:'.github/workflows/verify-impactrail-v9.yml',workflowSha256:'baccc20398a5161a1097c278473d914037f89b5ce230a06d472c4f0ecfe859ca',workflowRunId:'34336729341'};
const gateMethods=[['verify_package',1,'npm package'],['verify_run',2,'workflow run'],['verify_jobs',4,'completed jobs'],['verify_workflow',8,'workflow bytes']];
function App(){
 const[path,setPath]=useState(route()),[wallet,setWallet]=useState(null),[config,setConfig]=useState(null),[totals,setTotals]=useState(null),[record,setRecord]=useState(null),[form,setForm]=useState(defaults),[journal,setJournal]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[lookup,setLookup]=useState('0');
 const detail=path.match(/^\/grant\/(\d+)$/),current=config?.version===VERSION;
 const refresh=async()=>{if(!CONTRACT_ADDRESS)return;setConfig(await readContract('get_config'));setTotals(await readContract('get_accounting'));if(detail)setRecord(await readContract('get_grant',[BigInt(detail[1])]));};
 useEffect(()=>{const h=()=>setPath(route());window.addEventListener('hashchange',h);try{setJournal(loadJournal(localStorage));}catch(e){setError(e.message);}const reset=()=>{setWallet(null);setMessage('Wallet or network changed. Pending records remain journaled.');};window.ethereum?.on('accountsChanged',reset);window.ethereum?.on('chainChanged',reset);return()=>window.removeEventListener('hashchange',h);},[]);
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[path,message]);
 const persist=e=>{const n=loadJournal(localStorage).filter(x=>x.localId!==e.localId).concat(e);saveJournal(localStorage,n);setJournal(n);};
 async function reconcile(e){const receipt=await waitTransaction(makeReadClient(),e.hash,s=>setMessage(`Transaction ${s.status||'pending'}; verifying contract state…`));let id=e.grantId;if(e.method==='create_grant'&&id===undefined){const returned=receiptReadable(receipt);if(!Number.isInteger(Number(returned))||Number(returned)<0)throw Error('Create succeeded but grant ID was not readable. Journal retained.');id=String(returned);}let ok=e.method==='register_wallet'||e.method==='withdraw_unallocated';if(id!==undefined){const r=await readContract('get_grant',[BigInt(id)]);const bit=gateMethods.find(x=>x[0]===e.method)?.[1];ok=e.method==='create_grant'?sameAddress(r.sponsor,e.account)&&r.state==='DRAFT':e.method==='fund_grant'?r.state==='FUNDED':bit?((Number(r.gate_mask)&bit)===bit):e.method==='evaluate_grant'?['VERIFIED_CLAIMABLE','PARTIAL_CLAIMABLE','REFUND_CLAIMABLE'].includes(r.state):e.method==='expire_grant'?r.state==='EXPIRED_REFUND_CLAIMABLE':e.method==='withdraw'?BigInt(r.beneficiary_due)===0n||BigInt(r.sponsor_due)===0n:false;setRecord(r);go(`/grant/${id}`);}if(!ok)throw Error('Receipt finalized but expected V9 state was not confirmed. Journal retained.');persist({...e,grantId:id,phase:'VERIFIED'});setMessage('Execution, consensus and authoritative state readback verified.');return id;}
 async function send(method,args,meta={},value=0n){if(busy||!wallet||!current)return;setBusy(true);setError('');const e={localId:crypto.randomUUID(),network:NETWORK,contract:CONTRACT_ADDRESS,account:wallet.account,method,phase:'AWAITING_SIGNATURE',value:String(value),createdAt:new Date().toISOString(),...meta};try{persist(e);const hash=await writeContract(wallet,method,args,value);persist({...e,hash,phase:'PENDING'});return await reconcile({...e,hash,phase:'PENDING'});}catch(x){persist({...e,phase:'FAILED',error:x.message});setError(x.message||String(x));}finally{setBusy(false);}}
 async function create(ev){ev.preventDefault();try{if(!/^0x[0-9a-fA-F]{40}$/.test(form.beneficiary))throw Error('Beneficiary must be a wallet address.');for(const k of ['base','target','verificationCommit'])if(!/^[0-9a-fA-F]{40}$/.test(form[k]))throw Error('Commit IDs must be 40 hex characters without 0x.');for(const k of ['artifactSha256','workflowSha256'])if(!/^[0-9a-f]{64}$/.test(form[k]))throw Error('SHA-256 values must be 64 lowercase hex.');if(BigInt(form.minimumCommits)>250n)throw Error('Minimum commits cannot exceed the complete 250-commit bound.');const v=gen(form.amount);const id=await send('create_grant',[form.beneficiary,v,form.owner,form.repository,form.base,form.target,form.artifactPath,form.artifactSha256,form.releaseTag,form.milestone,BigInt(form.minimumCommits),BigInt(form.minimumContributors),BigInt(form.coverageStart),BigInt(form.duration),BigInt(form.partialBps),form.npmPackage,form.npmVersion,form.verificationCommit,form.workflowPath,form.workflowSha256,BigInt(form.workflowRunId)]);if(id!==undefined)await send('fund_grant',[BigInt(id)],{grantId:id},v);}catch(x){setError(x.message);}}
 const connect=async()=>{try{setWallet(await connectWallet());setError('');}catch(x){setError(x.message);}};
 const header=<header><a className="brand" href="#/"><img src="/impactrail-logo.png"/><span>ImpactRail<small>canonical impact gates</small></span></a><nav><a href="#/">Overview</a><a href="#/create">Create grant</a><a href="#/my">Find grant</a><a href="#/how">How it works</a></nav><button className="connect" onClick={connect}>{wallet?short(wallet.account):'Connect wallet'}</button></header>;
 const home=<><section className="hero"><div><p className="kicker">PUBLIC GOODS · VERIFIED ON GENLAYER</p><h1>Fund delivery you can <i>reproduce.</i></h1><p className="lede">Four independent canonical gates bind an npm release to a fixed GitHub commit and successful verification run before settlement.</p><div className="actions"><a className="primary" href="#/create">Create a grant ↗</a><a className="secondary" href="#/how">How it works</a></div></div><div className="hero-art"><img src="/impactrail-logo.png"/><div className="art-note"><b>{current?'V9 live contract':'Contract unavailable'}</b><span>{short(CONTRACT_ADDRESS)}</span></div></div></section><section className="stats">{[['Locked GEN','locked'],['Beneficiary claims','beneficiary_claimable'],['Sponsor claims','sponsor_claimable']].map(([l,k])=><div key={k}><span>{l}</span><strong>{totals?.[k]??'—'}</strong></div>)}</section></>;
 const keys=[['beneficiary','Beneficiary wallet'],['amount','GEN amount'],['owner','GitHub owner'],['repository','Repository'],['base','Base commit · 40 hex'],['target','Target commit · 40 hex'],['artifactPath','Artifact path'],['artifactSha256','Artifact SHA-256'],['releaseTag','Release tag'],['milestone','Objective milestone'],['minimumCommits','Minimum commits · max 250'],['minimumContributors','Minimum contributors'],['coverageStart','Coverage start · Unix seconds'],['duration','Evidence window · seconds'],['partialBps','Partial payout · basis points'],['npmPackage','npm package'],['npmVersion','Exact npm version'],['verificationCommit','Verification commit'],['workflowPath','Workflow path'],['workflowSha256','Workflow SHA-256'],['workflowRunId','Actions run ID']];
 const createPage=<section className="page"><p className="kicker">SEALED V9 GRANT</p><h2>Create, then explicitly fund</h2><form className="form" onSubmit={create}><fieldset><legend>Immutable terms</legend>{keys.map(([k,l])=><label key={k}>{l}{k==='milestone'?<textarea required value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>:<input required value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>}</label>)}</fieldset><button className="primary submit" disabled={busy||!wallet||!current}>Validate terms, then fund ↗</button><p className="hint">The value transaction occurs only after the non-payable draft is read back successfully.</p></form></section>;
 const find=<section className="page"><p className="kicker">AUTHORITATIVE READBACK</p><h2>Find a grant</h2><div className="form"><label>Grant ID<input type="number" min="0" value={lookup} onChange={e=>setLookup(e.target.value)}/></label><button onClick={()=>go(`/grant/${lookup}`)}>Read contract state</button></div></section>;
 const how=<section className="page how"><p className="kicker">V9 VERIFICATION</p><h2>Objective gates before judgment.</h2><div className="steps"><article><b>01</b><h3>Seal safely</h3><p>Reject unsupported thresholds before custody; funding is a separate call.</p></article><article><b>02</b><h3>Verify in stages</h3><p>npm identity, run, jobs and workflow bytes are independently fetched and bound to immutable terms.</p></article><article><b>03</b><h3>Settle deterministically</h3><p>Only all four gates permit final GitHub delivery evaluation and claim accounting.</p></article></div><div className="verification"><h3>Live lifecycle verified</h3><p>V9 reached PARTIAL_CLAIMABLE, paid beneficiary and sponsor, and finished with zero balance and zero claimable ledger.</p><a href={`${EXPLORER}/address/${CONTRACT_ADDRESS}`} target="_blank">Open deployed contract ↗</a></div></section>;
 const detailPage=<section className="page">{record?<><p className="kicker">GRANT #{record.id} · V9 READBACK</p><h2>{record.state.replaceAll('_',' ')}</h2><div className="record-card">{[['Gate mask',`${record.gate_mask}/15`],['Reason',record.reason||'—'],['Beneficiary due',record.beneficiary_due],['Sponsor due',record.sponsor_due]].map(([l,v])=><div key={l}><span>{l}</span><strong>{v}</strong></div>)}</div><div className="actions">{record.state==='DRAFT'&&<button disabled={busy||!wallet||!sameAddress(record.sponsor,wallet?.account)} onClick={()=>send('fund_grant',[BigInt(record.id)],{grantId:String(record.id)},BigInt(record.amount))}>Fund exact amount</button>}{record.state==='FUNDED'&&gateMethods.map(([m,bit,label])=><button key={m} disabled={busy||!wallet||(Number(record.gate_mask)&bit)!==0} onClick={()=>send(m,[BigInt(record.id)],{grantId:String(record.id)})}>Verify {label}</button>)}{record.state==='FUNDED'&&<button disabled={busy||!wallet||Number(record.gate_mask)!==15} onClick={()=>send('evaluate_grant',[BigInt(record.id)],{grantId:String(record.id)})}>Evaluate delivery</button>}{record.state.includes('CLAIMABLE')&&<button disabled={busy||!wallet} onClick={()=>send('withdraw',[BigInt(record.id)],{grantId:String(record.id)})}>Withdraw claim</button>}</div><details open><summary>Canonical gate evidence</summary><pre>{dump(record.gates)}</pre></details><details><summary>Sealed terms</summary><pre>{dump(record.terms)}</pre></details></>:<p>Loading canonical contract state…</p>}</section>;
 return <div className="shell">{header}<div className="network">Studionet · <a href={`${EXPLORER}/address/${CONTRACT_ADDRESS}`} target="_blank">{short(CONTRACT_ADDRESS)} ↗</a><span>{current?'IMPACT_RAIL_V9 confirmed':'Version mismatch: writes disabled'}</span></div>{message&&<p className="message">{message}</p>}{error&&<p className="error">{error}</p>}<main>{path==='/'&&home}{path==='/create'&&createPage}{path==='/my'&&find}{path==='/how'&&how}{detail&&detailPage}</main>{journal.length>0&&<section className="journal"><h3>Transaction journal</h3><p className="hint">Reconcile reads the receipt and contract state; it never resubmits.</p>{journal.slice(-10).reverse().map(e=><div className="journal-row" key={e.localId}><span><b>{e.method.replaceAll('_',' ')}</b> · {e.phase}</span>{e.hash&&<a href={`${EXPLORER}/tx/${e.hash}`} target="_blank">{short(e.hash)} ↗</a>}</div>)}</section>}<footer>ImpactRail · staged canonical verification</footer></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
