import {createClient,createAccount} from '../frontend/node_modules/genlayer-js/dist/index.js';
import {studionet} from '../frontend/node_modules/genlayer-js/dist/chains/index.js';
import {readFileSync,writeFileSync,existsSync,mkdirSync} from 'node:fs';
import {parse} from '../../TreasuryPayoutVerifier/scripts/testnet/node_modules/dotenv/lib/main.js';
const address=process.env.IMPACTRAIL_ADDRESS??'0x8bc22E809b85EF6568DD1083108F495f33d276FA';
const A='0xFeD97e2aE1A8C1983b7cA206B3545e6A2c685E43',B='0xc67532aeF9D2879cBA9375a02E6217A3524657B8',amount=1000000000000n;
const args=[B,amount,'macdon3202','IMPACTRAIL','4a3fd38f127ef54ccba668eafda02732d838fe4c','c526aa3faaa8299f571b8598f56423e77084178b','evidence/v6-npm-impact.md','117f86c86f786b1ac0f3de11efcb4181b00f9f21b5b868a1aa94e279fc82d612','impactrail-v6-npm-1.0.0','Publish the canonical ImpactRail npm package bound to the repository and commit with V9 validation and tests passing in the sealed GitHub Actions run.',1n,1n,1788430000n,900n,5000n,'@macdon3202/impactrail-canonical','1.0.0','19e1c7ee715f37cc1d7a23ba8df7695e9938de29','.github/workflows/verify-impactrail-v9.yml','baccc20398a5161a1097c278473d914037f89b5ce230a06d472c4f0ecfe859ca',34336729341n];
const dir=new URL('./.state/',import.meta.url);mkdirSync(dir,{recursive:true});const file=new URL('./.state/studionet-v9.json',import.meta.url);const enc=x=>JSON.stringify(x,(_,v)=>typeof v==='bigint'?String(v):v,2);let j=existsSync(file)?JSON.parse(readFileSync(file)):{address,actions:{}};const save=()=>writeFileSync(file,enc(j));
const reader=createClient({chain:studionet});const read=(fn,a=[])=>reader.readContract({address,functionName:fn,args:a});
function signer(w){const env=parse(readFileSync(new URL('../../secrets/genlayer-test-wallets.env',import.meta.url),'utf8')),raw=env['SERVICE_LEDGER_KEY_'+w].replace(/^<|>$/g,'').trim(),account=createAccount(raw.startsWith('0x')?raw:'0x'+raw),expected=w==='A'?A:B;if(account.address.toLowerCase()!==expected.toLowerCase())throw Error('WRONG_WALLET');return createClient({chain:studionet,account});}
async function receipt(hash){for(let i=0;i<80;i++){const tx=await reader.getTransaction({hash}),status=String(tx.statusName??'').toUpperCase();if(['FAILED','REJECTED','CANCELLED','UNDETERMINED'].includes(status))throw Error('TX_FAILED '+status);if(['ACCEPTED','FINALIZED'].includes(status)){const leaders=(tx.consensus_data?.leader_receipt??[]).filter(x=>x.result?.payload!=='idle');if(!leaders.length||leaders.some(x=>x.execution_result!=='SUCCESS'))throw Error('GENVM_ERROR '+hash);return {status,execution:'SUCCESS',consensus:'Accepted',result:leaders[0].result?.payload};}await new Promise(r=>setTimeout(r,3000));}throw Error('PENDING_NO_RESUBMIT');}
async function snap(){let grant=null;try{grant=await read('get_grant',[0n]);}catch{}return {config:await read('get_config'),accounting:await read('get_accounting'),grant,balance:await reader.getBalance({address})};}
async function send(name,w,fn,a=[],value=0n){if(j.actions[name]?.hash){j.actions[name].receipt=await receipt(j.actions[name].hash);j.actions[name].after=await snap();j.actions[name].phase='VERIFIED';save();return;}if(j.actions[name])throw Error('AMBIGUOUS_NO_RESUBMIT '+name);j.actions[name]={fn,args:a,value,phase:'SENDING',at:new Date().toISOString()};save();const hash=await signer(w).writeContract({address,functionName:fn,args:a,value});j.actions[name].hash=hash;j.actions[name].phase='SUBMITTED';save();j.actions[name].receipt=await receipt(hash);j.actions[name].after=await snap();j.actions[name].phase='VERIFIED';save();console.log(enc({name,hash,receipt:j.actions[name].receipt,grant:j.actions[name].after.grant,accounting:j.actions[name].after.accounting}));}
const action=process.argv[2]??'read';const initial=await snap();if(initial.config.version!=='IMPACT_RAIL_V9')throw Error('WRONG_VERSION '+initial.config.version);
if(action==='read')console.log(enc(initial));else if(action==='register')await send('register','B','register_wallet');else if(action==='create')await send('create','A','create_grant',args);else if(action==='fund')await send('fund','A','fund_grant',[0n],amount);else if(action==='package')await send('package','A','verify_package',[0n]);else if(action==='run')await send('run','A','verify_run',[0n]);else if(action==='jobs')await send('jobs','A','verify_jobs',[0n]);else if(action==='workflow')await send('workflow','A','verify_workflow',[0n]);else if(action==='evaluate')await send('evaluate','A','evaluate_grant',[0n]);else if(action==='withdraw')await send('beneficiary-withdraw','B','withdraw',[0n]);else if(action==='sponsor-withdraw')await send('sponsor-withdraw','A','withdraw',[0n]);else throw Error('UNKNOWN_ACTION');
