import {createClient,createAccount} from '../frontend/node_modules/genlayer-js/dist/index.js';
import {studionet} from '../frontend/node_modules/genlayer-js/dist/chains/index.js';
import {readFileSync,writeFileSync,existsSync,mkdirSync} from 'node:fs';
import {parse} from '../../TreasuryPayoutVerifier/scripts/testnet/node_modules/dotenv/lib/main.js';

const address=process.env.IMPACTRAIL_ADDRESS??'0xbD64f40726d717B0f436AAf7c85c2C1f46692838';
const A='0xFeD97e2aE1A8C1983b7cA206B3545e6A2c685E43';
const B='0xc67532aeF9D2879cBA9375a02E6217A3524657B8';
const amount=1000000000000n;
const args=[B,amount,'macdon3202','IMPACTRAIL','4a3fd38f127ef54ccba668eafda02732d838fe4c','c526aa3faaa8299f571b8598f56423e77084178b','evidence/v6-npm-impact.md','117f86c86f786b1ac0f3de11efcb4181b00f9f21b5b868a1aa94e279fc82d612','impactrail-v6-npm-1.0.0','Publish the canonical ImpactRail npm package bound to the sealed repository and commit, with its validation and tests passing in the sealed GitHub Actions run.',1n,1n,1788430000n,900n,5000n,'@macdon3202/impactrail-canonical','1.0.0','3469b3ff604d4e2d72bf1da3534f9bd427fd5d58','.github/workflows/verify-impactrail-v8.yml','a7d4b7201f5bef5a07da2eb4e3e6ad3176d181bf016d9cf95b55a15b97fff6e1',34328794332n];
const stateDir=new URL('./.state/',import.meta.url);mkdirSync(stateDir,{recursive:true});
const file=new URL('./.state/studionet-v8.json',import.meta.url);
const encode=x=>JSON.stringify(x,(_,v)=>typeof v==='bigint'?String(v):v,2);
let log=existsSync(file)?JSON.parse(readFileSync(file)):{address,version:'IMPACT_RAIL_V8',fixture:{verificationCommit:args[17],workflowRunId:String(args[20])},actions:{}};
const save=()=>writeFileSync(file,encode(log));
const reader=createClient({chain:studionet});
const read=(functionName,args=[])=>reader.readContract({address,functionName,args});
function signer(who){const env=parse(readFileSync(new URL('../../secrets/genlayer-test-wallets.env',import.meta.url),'utf8'));const raw=env['SERVICE_LEDGER_KEY_'+who].replace(/^<|>$/g,'').trim();const account=createAccount(raw.startsWith('0x')?raw:'0x'+raw);const expected=who==='A'?A:B;if(account.address.toLowerCase()!==expected.toLowerCase())throw Error('WRONG_WALLET');return createClient({chain:studionet,account});}
async function receipt(hash){for(let i=0;i<80;i++){const tx=await reader.getTransaction({hash});const status=String(tx.statusName??'').toUpperCase();if(['FAILED','REJECTED','CANCELLED','UNDETERMINED'].includes(status))throw Error('TX_FAILED '+hash+' '+status);if(['ACCEPTED','FINALIZED'].includes(status)){const leaders=(tx.consensus_data?.leader_receipt??[]).filter(x=>x.result?.payload!=='idle');if(!leaders.length||leaders.some(x=>x.execution_result!=='SUCCESS'))throw Error('EXECUTION_NOT_SUCCESS '+hash);const votes=Object.values(tx.consensus_data?.votes??{});if(votes.length&&votes.filter(x=>x==='agree').length<=votes.length/2)throw Error('CONSENSUS_NOT_VERIFIED '+hash);return {status,execution:'SUCCESS',consensus:'Accepted'};}await new Promise(r=>setTimeout(r,3000));}throw Error('TX_PENDING_NO_RESUBMIT '+hash);}
async function snapshot(){const config=await read('get_config'),accounting=await read('get_accounting'),accountA=await read('get_account',[A,0n]),accountB=await read('get_account',[B,0n]);let grant=null;if(Number(accountA.count)>0)grant=await read('get_grant',[0n]);return {config,accounting,accountA,accountB,grant,unallocatedA:await read('get_unallocated_refund',[A]),unallocatedB:await read('get_unallocated_refund',[B]),balances:{A:await reader.getBalance({address:A}),B:await reader.getBalance({address:B}),contract:await reader.getBalance({address})}};}
async function send(name,who,functionName,callArgs=[],value=0n,before=null){if(log.actions[name]?.hash){log.actions[name].receipt=await receipt(log.actions[name].hash);log.actions[name].after=await snapshot();log.actions[name].phase='VERIFIED';save();return log.actions[name];}if(log.actions[name])throw Error('AMBIGUOUS_SEND_NO_RESUBMIT '+name);log.actions[name]={functionName,args:callArgs,value,before:before??await snapshot(),phase:'SENDING',startedAt:new Date().toISOString()};save();const hash=await signer(who).writeContract({address,functionName,args:callArgs,value});log.actions[name].hash=hash;log.actions[name].phase='SUBMITTED';save();log.actions[name].receipt=await receipt(hash);log.actions[name].after=await snapshot();log.actions[name].phase='VERIFIED';save();console.log(encode({name,hash,grant:log.actions[name].after.grant,accounting:log.actions[name].after.accounting}));return log.actions[name];}
async function main(){const action=process.argv[2]??'read';const initial=await snapshot();if(initial.config.version!=='IMPACT_RAIL_V8')throw Error('WRONG_CONTRACT_VERSION '+initial.config.version);if(action==='read'){console.log(encode(initial));return;}if(action==='register'){await send('register-beneficiary','B','register_wallet',[],0n,initial);return;}if(action==='negative'){if(!log.actions['invalid-fund']?.hash){await send('invalid-fund','B','fund_grant',[999999n],amount,initial);return;}if(BigInt(initial.unallocatedB)!==amount||BigInt(initial.accounting.unallocated_claimable)!==amount)throw Error('INVALID_FUND_NOT_CREDITED');await send('recover-invalid-fund','B','withdraw_unallocated',[],0n,initial);return;}if(action==='create'){await send('create-draft','A','create_grant',args,0n,initial);return;}if(action==='fund'){await send('fund-draft','A','fund_grant',[0n],amount,initial);return;}if(action==='evaluate'){await send('evaluate','A','evaluate_grant',[0n],0n,initial);return;}if(action==='retry'){if(initial.grant?.state!=='INSUFFICIENT_EVIDENCE')throw Error('RETRY_STATE_MISMATCH '+initial.grant?.state);const attempt=Number(initial.grant.attempt_count);await send('retry-'+attempt,'A','retry_grant',[0n],0n,initial);return;}if(action==='expire'){await send('expire','A','expire_grant',[0n],0n,initial);return;}if(action==='refund'){await send('sponsor-withdraw','A','withdraw',[0n],0n,initial);return;}if(action==='withdraw'){await send('beneficiary-withdraw','B','withdraw',[0n],0n,initial);return;}throw Error('UNKNOWN_ACTION');}
main().catch(error=>{console.error(String(error.shortMessage??error.message).slice(0,4000));process.exitCode=1;});
