import {createClient,createAccount} from '../frontend/node_modules/genlayer-js/dist/index.js';
import {studionet} from '../frontend/node_modules/genlayer-js/dist/chains/index.js';
import {readFileSync,writeFileSync,existsSync,mkdirSync} from 'node:fs';
import {parse} from '../../TreasuryPayoutVerifier/scripts/testnet/node_modules/dotenv/lib/main.js';

const address=process.env.IMPACTRAIL_ADDRESS??'0xbA2DdBE10249E870EC2CF87A1b8C4e41553A995a';
const A='0xFeD97e2aE1A8C1983b7cA206B3545e6A2c685E43';
const B='0xc67532aeF9D2879cBA9375a02E6217A3524657B8';
const amount=1000000000000n;
const args=[B,amount,'macdon3202','IMPACTRAIL','ef0a23e4470dfaef0c38cfface89fcabf8225cd8','536091b33cb4c4a9cd45fb224277aa3c451889b3','evidence/impact-report.md','095b20d4e6274cdc27459e30ac1af114aadf86ee0ff0d2639f3cce1b5e4b01b0','impactrail-v4-fixture','Verify that owner-authored evidence cannot bypass independently fetched npm adoption.',1n,1n,1788430000n,120n,5000n,'impactrail-v6-canonical','1.0.0','2026-08-01','2026-08-31',1n];
const stateDir=new URL('./.state/',import.meta.url);mkdirSync(stateDir,{recursive:true});
const file=new URL('./.state/studionet-v6.json',import.meta.url);
const encode=x=>JSON.stringify(x,(_,v)=>typeof v==='bigint'?String(v):v,2);
let log=existsSync(file)?JSON.parse(readFileSync(file)):{address,fixture:{npmPackage:'impactrail-v6-canonical',expected:'NPM_SOURCE_UNAVAILABLE'},actions:{}};
const save=()=>writeFileSync(file,encode(log));
const reader=createClient({chain:studionet});
const read=(functionName,args=[])=>reader.readContract({address,functionName,args});
function signer(who){const env=parse(readFileSync(new URL('../../secrets/genlayer-test-wallets.env',import.meta.url),'utf8'));const raw=env['SERVICE_LEDGER_KEY_'+who].replace(/^<|>$/g,'').trim();const account=createAccount(raw.startsWith('0x')?raw:'0x'+raw);const expected=who==='A'?A:B;if(account.address.toLowerCase()!==expected.toLowerCase())throw Error('WRONG_WALLET');return createClient({chain:studionet,account});}
async function receipt(hash){for(let i=0;i<60;i++){const tx=await reader.getTransaction({hash});const status=String(tx.statusName??'').toUpperCase();if(['FAILED','REJECTED','CANCELLED','UNDETERMINED'].includes(status))throw Error('TX_FAILED '+hash+' '+status);if(['ACCEPTED','FINALIZED'].includes(status)){const leaders=(tx.consensus_data?.leader_receipt??[]).filter(x=>x.result?.payload!=='idle');if(!leaders.length||leaders.some(x=>x.execution_result!=='SUCCESS'))throw Error('EXECUTION_NOT_SUCCESS '+hash);const votes=Object.values(tx.consensus_data?.votes??{});if(votes.filter(x=>x==='agree').length<=votes.length/2)throw Error('CONSENSUS_NOT_VERIFIED '+hash);return tx;}await new Promise(r=>setTimeout(r,3000));}throw Error('TX_PENDING_NO_RESUBMIT '+hash);}
async function snapshot(){const config=await read('get_config'),accounting=await read('get_accounting'),accountA=await read('get_account',[A,0n]),accountB=await read('get_account',[B,0n]);let grant=null;if(Number(accountA.count)>0)grant=await read('get_grant',[0n]);return {config,accounting,accountA,accountB,grant,balances:{A:await reader.getBalance({address:A}),B:await reader.getBalance({address:B}),contract:await reader.getBalance({address})}};}
async function send(name,who,functionName,callArgs=[],value=0n){if(log.actions[name]?.hash){log.actions[name].receipt=await receipt(log.actions[name].hash);log.actions[name].after=await snapshot();log.actions[name].phase='VERIFIED';save();return;}if(log.actions[name])throw Error('AMBIGUOUS_SEND_NO_RESUBMIT '+name);log.actions[name]={functionName,args:callArgs,value,before:await snapshot(),phase:'SENDING',startedAt:new Date().toISOString()};save();const hash=await signer(who).writeContract({address,functionName,args:callArgs,value});log.actions[name].hash=hash;log.actions[name].phase='SUBMITTED';save();log.actions[name].receipt=await receipt(hash);log.actions[name].after=await snapshot();log.actions[name].phase='VERIFIED';save();console.log(encode({name,hash,state:log.actions[name].after.grant?.state,accounting:log.actions[name].after.accounting}));}
async function main(){const action=process.argv[2]??'read';const initial=await snapshot();if(initial.config.version!=='IMPACT_RAIL_V6')throw Error('WRONG_CONTRACT');if(action==='read'){console.log(encode(initial));return;}if(action==='register'){await send('register','B','register_wallet');return;}if(action==='fund'){await send('fund','A','create_grant',args,amount);return;}if(action==='evaluate'){await send('evaluate','A','evaluate_grant',[0n]);const after=await snapshot();if(after.grant?.state!=='INSUFFICIENT_EVIDENCE'||after.grant?.reason!=='NPM_SOURCE_UNAVAILABLE'||after.accounting.locked!==String(amount))throw Error('FAIL_CLOSED_READBACK_MISMATCH');return;}if(action==='recover'){let current=await snapshot();if(Math.floor(Date.now()/1000)<Number(current.grant?.deadline??0))throw Error('WINDOW_OPEN_UNTIL '+current.grant.deadline);await send('expire','A','expire_grant',[0n]);await send('refund','A','withdraw',[0n]);current=await snapshot();log.final=current;save();if(current.grant?.state!=='PAID'||current.accounting.locked!=='0'||current.accounting.sponsor_claimable!=='0'||current.balances.contract!==0n)throw Error('FINAL_READBACK_MISMATCH');console.log(encode({complete:true,final:current}));return;}throw Error('UNKNOWN_ACTION');}
main().catch(error=>{console.error(String(error.shortMessage??error.message).slice(0,3000));process.exitCode=1;});
